### PR TITLE
Fix deprecations

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by lsmith77** [comment]
just for the record .. there are still some deprecations left even after this PR :-/

**Comment by WouterJ** [comment]
@lsmith77 yeah, we can't change security context in Corebundle 1.x (see #170 for the issue about doing it for 2.0). The other deprecation notices are coming from usage of the type name in tests, I don't think it's worth fixing that (users won't see these notices).

**Comment by lsmith77** [comment]
I see .. would be good to be 2.8 compatible though .. and right now all repos seem to fail on 2.8 .. let alone 3.0 .. many of which not only due to deprecations but due to tests returning 500'ers

**Comment by WouterJ** [comment]
@lsmith77 we will be 2.8 compatible, just with some deprecations. It's almost impossible to support 2.3 *and* 3.0 at the same time. 2.3 is just too old to achieve it.

The 500 pages are caused by https://github.com/sonata-project/SonataAdminBundle/pull/3267 .

For 3.0 support, I thought we agreed a while ago on releasing CMF 2.0 after CMF 1.3, which will require PHP >=5.5 and Symfony >=2.8/2.7.

**Comment by lsmith77** [comment]
Yeah .. 3.0 is a CMF 2.0 topic.

**Pull request merged**
