### PR TITLE
Improved twig performance

### PR DESCRIPTION
**Pull request by WouterJ**
I'm not sure how much or why, but using extension methods seem to improve performance enough to make @stof recommend to do this duplication. See also https://github.com/KnpLabs/KnpMenu/pull/189#discussion_r22474664

### CODE REVIEW

**Comment by stof** [comment]
note that this improves it when **all** Twig functions being used are either using extension methods of PHP functions (either global functions or static methods). This is because in these 2 cases, Twig can generate an optimized way to access the callable in the compiled template without requiring to initialize all extensions fully.

**Comment by dbu** [comment]
@stof that means that all twig extensions always should offer a local method for each twig function for performance reasons? and if the whole project has one single function that is not that way the performance is lost? or only with templates that use the violating extension?

makes me wonder if we should not have a compiler pass (not in the cmf) that builds extension proxy classes for this to avoid boilerplate code like the one being added here.

and just to be sure, you are +1 to merge this PR as is @stof , or is something missing?

**Comment by stof** [comment]
@dbu only for templates using the affected function (the first time such a function is used, the initialization is triggered)

Note that this should probably be profiled though to see whether the proxying call adds more or less overhead (I don't remember whether it really adds a call given that other calls are changed too). It might be worth a blackfire profile comparison

**Comment by stof** [comment]
has it been profiled ?

**Pull request merged**
